#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 2013-2015 Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANT ABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
# ----------------------------------------------------------------------
source tuirc
ME=$(basename "${DEST/.1/}")

cat > "$DEST" << EOF
.ig
$ME - short description
Copyright (C) $(date +'%B %d') by $USER_NAME - $USER_EMAIL
.. ....................................................
.TH "$ME" 1 "$(date +'%F'|sed s/'\.'/' '/g)" "$USER_NAME"



.SH NAME
$ME (0.1)



.SH SYNOPSIS
\fB$ME\fP 
.OP option
.RI arguments
.br

Example:	$ME filename
.br
		$ME
.OP -v
.OP -l label
filename
.br




.SH OPTIONS
.br
.OP "-v"
Optional option
.br

.OP "-l label" 
Bold option with argument

.IP "\fB-XY\fP" 
Bold option
.br



.SH DESCRIPTION
Some descriptional text
.br
.B 1.
Listing text
.br
.B 2.
Listing text
.br
.IP "\fBList Heading\fP"
Some descriptional text
.RS 11
.B 3.
Indented
.I list
.br
.B 4.
Indented 
.B list
.RS 4
.B 5.
Sub ident
.RE



.SH SEE ALSO
.B bash
(1),
.B man
(1),
.B tui
(1)



.SH LICENSE
$DEFAULT_LICENSE
.br
$DEFAULT_LICENSE_URL



.SH CONTACT
$USER_EMAIL
.br
$USER_HOMEPAGE



.SH BUG REPORTS
Please visit "$USER_HOMEPAGE" to report bugs, or send me an email to the adress listed in
.B
CONTACT
EOF