#!/bin/bash
#source tui
ME=$(basename "${DEST/.1/}")

cat > "$DEST" << EOF
.TH "$ME" "1" "$(date +'%F'|sed s/'\.'/' '/g)" "$USER_NAME"

.SH NAME
$ME (0.1)

.SH SYNOPSIS
\fB$ME\fP [options] [arguments]
.br
Example: $ME
.br
Where options are:
.IP "\fB-XY\fP"
does this
.IP "\fB-YX\fP"
does that

.SH DESCRIPTION
.PP
Some descriptional text

.SH LICENSE
$DEFAULT_LICENSE
.br
$DEFAULT_LICENSE_URL

.SH CONTACT
$USER_EMAIL
.br
$USER_HOMEPAGE
EOF
