#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 2013-2015 Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANT ABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
# ----------------------------------------------------------------------
source tuirc
ME=$(basename "${DEST/.1/}")

cat > "$DEST" << EOF
.TH "$ME" "1" "$(date +'%F'|sed s/'\.'/' '/g)" "$USER_NAME"

.SH NAME
$ME (0.1)

.SH SYNOPSIS
\fB$ME\fP [options] [arguments]
.br
Example: $ME
.br
Where options are:
.IP "\fB-XY\fP"
does this
.IP "\fB-YX\fP"
does that

.SH DESCRIPTION
.PP
Some descriptional text

.SH LICENSE
$DEFAULT_LICENSE
.br
$DEFAULT_LICENSE_URL

.SH CONTACT
$USER_EMAIL
.br
$USER_HOMEPAGE
EOF
