.TH "tui-bol-dir" 1  "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-bol-dir

.SH SYNOPSIS
\fBtui-bol-dir\fP /path/to/check

.SH DESCRIPTION
Returns 0 if /path/to/check exists
.br
Returns 0 if /path/to/check doesnt exist and could be created
.br
Returns 1 if /path/to/check doesnt exist but could not be created

.SH SEE ALSO
bash (1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org