.TH "tui-bol-sudo" "1" "2015-01-07" "Simon Arjuna Erat (sea)"

.SH NAME
tui-bol-sudo (0.1)

.SH SYNOPSIS
\fBtui-bol-sudo\fP [options] [arguments]
.br
Example: tui-bol-sudo
.br
Where options are:
.IP "\fB-h\fP"
Show the help text

.SH DESCRIPTION
.PP
Returns a simple bool integer.
.br
.I -1
	When no
.B
sudo 
was found.
.br
.I 0
	 When sudo is installed and user has sudo or is root
.br
.I 1
	 When sudo was found, but user may not use sudo.

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
