.TH "tui-read" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"

.SH NAME
tui-read

.SH SYNOPSIS
\fBtui-read\fP [options] "Question"
.br
Example: MYHAIR=$(tui-read "what color is your hair?")

.SH DESCRIPTION
.PP
Some descriptional text

.SH SEE ALSO
read(1), sh(1)

.SH LICENSE
GNU Lesser General Public License (LGPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org