.TH "tui-bgjob" "1" "2013 10 26" "Simon A. Erat (sea)"

.SH NAME
tui-bgjob (0.2)

.SH SYNOPSIS
\fBtui-bgjob\fP SCRIPTFILE  'Progress String'  'Exit String'  [ WAIT ]
.br
NOTE:\t'Progress String' may contain shell escaped commands.
.br
Example1: tui-bgjob $HOME/script.sh "\\$(ls -l \\$some_var/FILE|awk '{print \\$5}')" "Script executed"
.br
Example2: tui-bgjob scriptname "Working, please wait..." "Finished" 5
.SH DESCRIPTION
.PP
Executes SCRIPTFILE and prints 'Progress String' while running.
.br
Prints 'Exit String' when done, regardless of exit code (0,1,?).
.br
WAIT is the optinal wait time in seconds between updates, default is 0.7.

.SH SEE ALSO
ps(1), sh(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org