.TH "tui-math-add" "1" "2015-06-04" "sea"

.SH NAME
tui-math-add (0.1)

.SH SYNOPSIS
\fBtui-math-add\fP NUM1 NUM2 [ NUM3 ... ]
.br
Example:	tui-math-add 2.5 1.75
.br
		4.25
.br
Where options are:
.IP "\fB-h\fP"
Help Screen

.SH DESCRIPTION
.PP
Adds up numbers

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com/
