.TH "tui-new-browser" "1" "2014 04 26" "Simon Arjuna Erat (sea)"

.SH NAME
tui-new-browser (0.1)

.SH SYNOPSIS
\fBtui-new-browser\fP [options] [arguments]
.br
Example: tui-new-browser
.br
Where options are:
.IP "\fB-XY\fP"
does this
.IP "\fB-YX\fP"
does that

.SH DESCRIPTION
.PP
Some descriptional text

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://sea.fedorapeople.org
