.TH "tui-indi" 1 "Simon A. Erat (sea)" "TUI 0.6.0"


.SH NAME
tui-indi (0.)

.SH SYNOPSIS
\fBtui-indi\fP
.br

Example:
.br
		while [ true ];do tui-printf $(
.B tui-indi
);done
.br

.SH DESCRIPTION
.PP
Each call it prints the next symbol of this order:
.br
- \\ | /
.br
So it can easy be used to 'indicate' progress while remain on the same line.

.SH SEE ALSO
bash(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com