.TH "tui-math-sqr" "1" "2015-06-04" "sea"

.SH NAME
tui-math-sqr (0.1)

.SH SYNOPSIS
\fBtui-math-sqr\fP NUM1 [ NUM2 NUM3 ... ]
.br
Example:	tui-math-sqr 25 9 10
.br
		5
.br
		3
.br
		3.16228
.br
Where options are:
.IP "\fB-h\fP"
Help Screen

.SH DESCRIPTION
.PP
Takes the square root of passed numbers

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com/
