.TH "tui-wait" "1" "" "Simon Arjuna Erat (sea)"

.SH NAME
tui-wait (0.1)

.SH SYNOPSIS
\fBtui-wait\fP [options] [arguments]
.br
Example: tui-wait
.br
Where options are:
.IP "\fB-XY\fP"
does this
.IP "\fB-YX\fP"
does that

.SH DESCRIPTION
.PP
Some descriptional text

.SH LICENSE
GNU Lesser General Public License (LGPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://sea.fedorapeople.org
