.TH "tui-header" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-header (0.7)


.SH SYNOPSIS
\fBtui-header\fP [STRING1] [STRING2] [STRING3]
.br

Example:
.br
		\fBtui-header\fP 'left'
.br
		\fBtui-header\fP '' 'center' 'right'
.br
		\fBtui-header\fP 'left'  'right'
		

.SH DESCRIPTION
Prints the complete line 
.B blue
and writes with 
.B white
text.
.br
Prints supplied STRING[1-3] aligned according to their position encapsuled by BORDER_LEFT and BORDER_RIGHT and prints a newline.
.br
STRING1 : LEFT
.br
STRING2 : RIGHT (or middle if 3)
.br
STRING3 : RIGHT
.br

.SH FILES
.IP /etc/tui/tui.conf
Provies the color names used by the
.B THEMES

.IP /usr/share/tui/themes/*
Provides the configurations for the
.B THEMES
used.

.IP /etc/tui/tui.conf
Provides the default theme 
.IP ~/.config/tui/user.conf
Provides the THEME the user uses.


.SH SEE ALSO
.B bash
(1),
.B tui-printf
(1),
.B tput
(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org