.TH "tui-str-usb" "tui-status" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-str-usb (0.2)

.SH SYNOPSIS
\fBtui-str-usb\fP [-a]
.br

Example: 
.br
		DEVICE=$(\fBtui-str-usb\fP)

.SH OPTIONS
.OP -a
Autoselect if only 1 entry found

.SH DESCRIPTION
Returns /dev/sd[a-z]
.br
Scans for /dev/disk/by-id for entries starting with USB.
.br
If no device is found, asks the user to plug in one.
.br
When one is found, lets the user select among available.
.br
Does return first found automaticly if only one available.

.SH SEE ALSO
ls(1), readlink(1), bash(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com