.TH "tui-yesno" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"

.SH NAME
tui-yesno

.SH SYNOPSIS
\fBtui-yesno\fP "Question"

.br
Example: 
.br
if \fBtui-yesno\fP "Are you male?"
.br
then echo "do male stuff"
.br
else echo "do female stuff"
.br
fi

.SH DESCRIPTION
.PP
Asks the user supplied question and returns 0 for y,j,o,s
.br
which are the starting letters for yes in english, spanish, italian, german and french
.br
or 1 for anything else.

.SH SEE ALSO
read(1), sh(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org