.TH "tui-str-usb" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"

.SH NAME
tui-str-usb

.SH SYNOPSIS
\fBtui-str-usb\fP
.br
Example: tui-str-usb 


.SH DESCRIPTION
.PP
Scans for /dev/disk/by-id for entries starting with USB.
.br
If no device is found, asks the user to plug in one.
.br
When one is found, lets the user select among available.
.br
Does return first found if only one available.

.SH SEE ALSO
ls(1), readlink(1), sh(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org