.TH "tui-download" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"

.SH NAME
tui-download

.SH SYNOPSIS
\fBtui-download\fP [options] URL [URL2] ..
.br
Example: tui-download www.someadress.com/file.ext www.someadress.com/file2.ext 

.SH DESCRIPTION
.PP
Tries to download each passed argument to 'current' directory

.SH LICENSE
GNU Lesser General Public License (LGPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT
< simon @ localhost.localdomain >
.br

