.TH "tui-title" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"

.SH NAME
tui-title

.SH SYNOPSIS
\fBtui-title\fP [STRING1] [STRING2] [STRING3]

.SH DESCRIPTION
.PP
Prints BORDER_LEFT and BORDER_RIGHT without the terminal's default colors
.br
Fills the text part with TITLE_BG and writes with TITLE_FG

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT
erat.simon@gmail.com
.br
sea@fedoraproject.org
