.TH "cli-newscript" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"

.SH NAME
cli-newscript

.SH SYNOPSIS
\fBcli-newscript\fP [/path/to/]SCRIPTNAME

.SH DESCRIPTION
.PP
Places SCRIPTNAME in ~/bin or absolute path if provided [/path/to].

.SH LICENSE
GNU Lesser General Public License (LGPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT
erat.simon@gmail.com
.br
sea@fedoraproject.org
