.TH "tui-config-editor" "1" "2014-11-03" "Simon Arjuna Erat (sea)"

.SH NAME
tui-config-editor (0.1)

.SH SYNOPSIS
\fBtui-config-editor\fP [options] [arguments]
.br
Example: tui-config-editor
.br
Where options are:
.IP "\fB-XY\fP"
does this
.IP "\fB-YX\fP"
does that

.SH DESCRIPTION
.PP
This is a basic configuration editor.
.br
It does only work with plain text, offers no selection menus.
.br
If you want something more advanced, feel free to look into the code and adapt to your scripts.

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://sea.fedorapeople.org
