.TH "tui-download" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-download

.SH SYNOPSIS
\fBtui-download\fP [options] URL [URL2] ..
.br

Example:
.br
		tui-download www.someadress.com/file.ext www.someadress.com/file2.ext 

.SH DESCRIPTION
Downloads all passed arguments to current directory

.SH SEE ALSO
wget(1), bash(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com