.TH "tui-newscript" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"

.SH NAME
tui-newscript

.SH SYNOPSIS
\fBtui-newscript\fP [/path/to/]SCRIPTNAME

.SH DESCRIPTION
.PP
Places SCRIPTNAME in ~/bin or absolute path if provided [/path/to].

.SH SEE ALSO
sh(1), man(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org
