.TH "tui-str-extension" "1" "2015-05-06" "Simon Arjuna Erat (sea)"

.SH NAME
tui-str-extension (0.1)

.SH SYNOPSIS
\fBtui-str-extension\fP [options] [arguments]
.br
Example: tui-str-extension "file name.string.txt"
.br
Where options are:
.IP "\fB-h\fP"
Shows the helpscreen

.SH DESCRIPTION
.PP
Simply returns the string after the last dot.
.br
Returns empty string if no dots were found.

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
