.TH "tui-str-genfilename" "1"  "Simon A. Erat (sea)" "TUI 0.7.3"

.SH NAME
tui-str-genfilename (0.2)

.SH SYNOPSIS
\fBtui-str-genfilename\fP [options] [/path/to/]filename [new_ext]
.br
Example: tui-str-genfilename tempfile \$\$
.br
Where options are:
.IP "\fB-h\fP"
Shows the help screen
.IP "\fB-v\fP"
Be verbose

.SH DESCRIPTION
.PP
It takes given filename and looks if it exits, if there is such a file,
it inserts an increasing number until no file with this name is found.
.br
That name not found is returned.
.br
If the filename contains dots, the last string is considered as old file extension, and is either replaced by the
.B new_ext
or the number is inserted before that.

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
