.TH "tui-yesno" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-yesno (0.4)

.SH DESCRIPTION
Asks the user supplied question and returns 0 (true) for 
.B y,j,o,s
which are the starting letters for
.I yes
in english, spanish, italian, german and french.
.br
Returns 1 (false) for anything else.

.SH SYNOPSIS
\fBtui-yesno\fP "Question"

.br
Example: 
.br
if \fBtui-yesno\fP "Are you male?"
.br
then echo "do male stuff"
.br
else echo "do female stuff"
.br
fi


.SH SEE ALSO
read(1), bash(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org