.TH "tui-echo" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"


.SH NAME
tui-echo
.br


.SH SYNOPSIS
\fBtui-echo\fP [STRING1] [STRING2] [STRING3]
.br


.SH DESCRIPTION
.PP
Prints supplied STRING[1-3] aligned according to their position encapsuled by BORDER_LEFT and BORDER_RIGHT and sends cur
.br
STRING1 : LEFT
.br
STRING2 : RIGHT (or middle if 3)
.br
STRING3 : RIGHT
.br

.SH SEE ALSO
printf(1), sh(1), tput(1)

.SH LICENSE
GNU Lesser General Public License (LGPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org