.TH "tui-new-browser" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-new-browser (0.3)

.SH SYNOPSIS
\fBtui-new-browsert\fP [Projecttitle]
.br

.SH DESCRIPTION
Helps you to create a new project based on
.B tui-browser
.br

.SH SEE ALSO
.B tui-browser
(1),
.B tui-new-script
(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://sea.fedorapeople.org
