.TH "tui-value-get" "1" "2014 04 24" "Simon Arjuna Erat (sea)"

.SH NAME
tui-value-get (0.1)

.SH SYNOPSIS
\fBtui-value-get\fP [options] [arguments]
.br
Example: 	tui-value-get    /etc/default/grub GRUB_CMDLINE_LINUX
.br
		tui-value-get -i /etc/default/grub grub_cmdline_linux
.br
		tui-value-get -l /etc/default/grub

.br
Where options are:
.IP "\fB-l|--list\fP"
Shows a list of all variables available in the file.
.IP "\fB-i|--irrelevant\fP"
Whether the variable name is provided in capitals or not is no longer relevant.

.SH DESCRIPTION
.PP
tui-value-get was designed to ease a developers task on getting values of variables.
.br
As of current state it removes any occouring '"' or '=' in the string returning.

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://sea.fedorapeople.org
