.TH "tui-cat" "1" "2015-01-21" "Simon Arjuna Erat (sea)"

.SH NAME
tui-cat (0.4)

.SH SYNOPSIS
\fBtui-cat.1\fP [options] [arguments [...]]
.br
Example:	tui-cat [/path/to/]file
.br
		tui-cat -td 0.5 "Message string" "[/path/to/]file.txt" "Second string" [...]
.br

Where options are:
.IP "\fB-t\fP"
Enables typerwriter mode
.IP "\fB-d 0.002\fP"
Typerwrite mode only, sets the delay between a character is printed.

.SH DESCRIPTION
.PP
Simply prints the content of a file within TUI borders.
.br
If typewriter mode is enabled, one can pass strings too.
.br

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
