.TH "tui-math-div" "1" "2015-06-04" "sea"

.SH NAME
tui-math-div (0.1)

.SH SYNOPSIS
\fBtui-math-div\fP NUM1 NUM2 [ NUM3 ... ]
.br
Example:	tui-math-div 10 3
.br
		3.3333
.br
Where options are:
.IP "\fB-h\fP"
Help Screen

.SH DESCRIPTION
.PP
Divides passed numbers

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com/
