.TH "tui-header" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"

.SH NAME
tui-header

.SH SYNOPSIS
\fBtui-header\fP [STRING1] [STRING2] [STRING3]

.SH DESCRIPTION
.PP
Fills the complete line with HEAD_BG and writes with HEAD_FG

.SH SEE ALSO
printf(1), sh(1), tput(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org