.TH "tui-psm" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
Paralell Script Manager (0.7.2)

.SH DESCRIPTION
Executes as many scripts as you pass to it.
.br
Can also return the number of successfully ended scripts as exit code.
.br

.SH SYNOPSIS
\fBtui-psm\fP [options] [arguments]
.br

Examples:
.br
		\fBtui-psm\fP script1 script2
.br
		\fBtui-psm\fP -cl 5 *
.br
	
.br

.SH OPTIONS
.OP -c
.RS 4
Returns the number of successfully executed (as in ended) scripts as exit code.
.RE

.OP -l NUM
.RS 4
Limits the number of paralell executed scripts.
.br
5 is default
.br
0 to disable
.RE

.OP -w NUM
.RS 4
Wait NUM seconds between value updates.
.br
The lower the number, the more intense the cpu usage will be.
.br
The default is 5 seconds.
.RE

.OP -q NUM
.RS 4
Be quiet
.br
Just silent and non-verbose.
.RE



.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html
.br

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
.br
