.TH "tui-wait" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-wait (0.4)

.SH DESCRIPTION
Waits for provided time and shows the user a message if provided.
.br
Append either a 'm' or 'h' to wait for NUM 'minutes' or 'hours'.

.SH SYNOPSIS
\fBtui-wait\fP NUM[mh] ["Messsage to user"]
.br

Example:
.br
		tui-wait 4m "Message to user"
.br


.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://sea.fedorapeople.org
