.TH "tui-indi" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"


.SH NAME
tui-indi

.SH SYNOPSIS
\fBtui-indi\fP
.br
Example: 
while [ true ];do tui-printf $(tui-indi);done

.SH DESCRIPTION
.PP
Each call it prints the next symbol of this order:
.br
- \\ | /

.SH SEE ALSO
sh(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org