.TH "tui-web" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-web (0.6)

.SH SYNOPSIS
\fBtui-web\fP [options] URL1 URL2
.br

Example: 
.br
		\fBtui-web\fP google.com
.br
		\fBtui-web\fP *html

.SH DESCRIPTION
Opens provided URL in BROWSER
.br

As not all browsers support the opening of multiple loactions at once, when passing multiple locations, it will loop through all of them calling the web browser for each of them.

.SH OPTIONS
.PP
.OP -m MODE
Forces to use application according to passed MODE, where MODE is either
.B cli
or
.B gui

.SH FILES
.IP /etc/tui/apps.conf
Provides the favorite applications defaults for the system.
.IP ~/.config/tui/apps.conf
Provides the favorite applications defaults for the user.


.SH SEE ALSO
.B bash
(1),
.B tui
(1),
.B tui-edit
(1),
.B tui-filemngr
(1),
.B tui-terminal
(1),
.B tui-web
(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com