.TH "tui-tar" "1" "2013 09 29" "Simon A. Erat (sea)" "tui-tar 0.1"

.SH NAME
tui-tar

.SH SYNOPSIS
\fBtui-tar\fP [options] [[/path/to/]tar] [[/path/to/]tar2] ...
.br
Example: tui-tar /some/dir /some/{reg,ex}
.br
NOTE: Wildcards only will fail
Where options are:
.br
.IP "\fB-h\fP"
Shows this
.br


.SH DESCRIPTION
.PP
Tar's provided /path/to/tar or asks for it.
.br
Tarball is placed within current (pwd) path.

.SH LICENSE
GNU Lesser General Public License (LGPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT
erat.simon@gmail.com
.br

