.TH "tui-edit" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"


.SH NAME
tui-edit

.SH SYNOPSIS
\fBtui-edit\fP [options] [/path/to/]FILE [../]FILE2 ...
.br
Example: 
.br
tui-edit testfile.txt

.SH DESCRIPTION
Opens provided FILE/s in EDITOR_[CLI,GUI]

.SH LICENSE
GNU Lesser General Public License (LGPL)
.br
http://www.gnu.org/licenses/lgpl.html


.SH CONTACT
erat.simon@gmail.com
