.TH "tui-printf" 1 "Simon A. Erat (sea)" "TUI 0.6.0"


.SH NAME
tui-printf (0.9.7)


.SH SYNOPSIS
\fBtui-printf\fP [options] [STRING1] [STRING2] [STRING3]
.br

Example:
.br
		\fBtui-printf\fP 'left'
.br
		\fBtui-printf\fP '' 'center' 'right'
.br
		\fBtui-printf\fP 'left'  'right'

.SH DESCRIPTION
.PP
Prints supplied STRING[1-3] aligned according to their position encapsuled by BORDER_LEFT and BORDER_RIGHT and prints a 
.B "return to linestart."
.br
STRING1 : LEFT
.br
STRING2 : RIGHT (or middle if 3)
.br
STRING3 : RIGHT
.br

.SH OPTIONS
.OP -E
.br
.B tui-echo
is actualy a handler for
.B "tui-printf -E"

.OP -H
.br
.B tui-header
is actualy a handler for
.B "tui-printf -H"

.OP -T
.br
.B tui-title
is actualy a handler for
.B "tui-printf -T"

.SH FILES
.IP /etc/tui/tui.conf
Provies the color names used by the
.B THEMES

.IP /usr/share/tui/themes/*
Provides the configurations for the
.B THEMES
used.

.IP /etc/tui/tui.conf
Provides the default theme 
.IP ~/.config/tui/user.conf
Provides the THEME the user uses.


.SH SEE ALSO
.B bash
(1),
.B tui
(1),
.B tput
(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com