.TH "tui-read" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-read (0.7)

.SH SYNOPSIS
\fBtui-read\fP [-p] "Question"
.br

Examples:
.br
		MYHAIR=$(tui-read "what color is your hair?")
.br
		PASSWORD=$(tui-read -p "Enter your password:"
.br

.SH DESCRIPTION
Simply reads the input given by user while showing him the 'Question'.

.SH OPTIONS
.OP -p
.RS 4
Wont show characters typed in.
.RE

.SH SEE ALSO
read(1), bash(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com