.TH "tui-rnd" "1" "2015-01-12" "Simon Arjuna Erat (sea)"

.SH NAME
tui-rnd (0.1)

.SH SYNOPSIS
\fBtui-rnd\fP [-h] [MAX=100] [MIN=0]
.br
Example: 	tui-rnd
.br
		tui-rnd 50
.br
		tui-rnd 9999 1000
.br

.SH DESCRIPTION
.PP
A simple tool which returns a random number between 0 and 100.
.br
You may give it either a MAX number only, or a range passing MAX and MIN values.
.br

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
