.TH "tui-edit" "1" "2013 09 15" "Simon A. Erat (sea)" "TUI 0.4.0"


.SH NAME
tui-edit

.SH SYNOPSIS
\fBtui-edit\fP [options] [/path/to/]FILE [../]FILE2 ...
.br
Example: 
.br
tui-edit testfile.txt

.SH DESCRIPTION
Opens provided FILE/s in EDITOR_[CLI,GUI]

.SH SEE ALSO
sh(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://sea.fedorapeople.org