.TH "tui-progress" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-progress (0.3)

.SH SYNOPSIS
\fBtui-progress\fP [options] [MESSAGE]
.br

Example:
.br
		tui-progress "Message to user"
.br
		tui-progress -m 104 "Count up to 104"
.br

.SH OPTIONS
.OP -i WORD
.RS 4
Uses WORD as describor and tempfile name for the progress index.
.br
This is specialy helpfull when running several scripts in the background where numbering for each is enabled.
.RE

.OP \fB-r\fP
.RS 4
Resets the tempfile which is diffrent if
.B -i WORD
is provided.
.RE

.OP -m MAXVAL
.RS 4
Set Max value to MAXVAL, this changes the output to: counted: 'num / max', where 'num' is the number of item currently worked on.
.br
Note that this option requires a prior invoke of:
.B "tui-progress -ri APPNAME -m 104"
.br
whereby followed by
.B "tui-progress -i APPNAME 'Text of Task: $FILENAME'"
.br
Which will be shown similar to:
.br

# | Text of Task: Currentfile.txt	 	 	 	CUR / 104 | #
.br

Where
.B CUR
is the current number of the invoke of 
.B "tui-progress -i APPNAME 'Text of Task: $FILENAME'"
which is saved and increased from the tempfile 'APPNAME'.
.RE

.OP -v
.RS 4
Will enable verbose mode, but only applies when
.B "-m NUM"
is inovked.
.RE

.SH DESCRIPTION
.PP
Is used to indicate progress, while keeping the output to a single line.

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
