.ig
TUI - Text User Interface
Copyright (C) November 2014 by Simon Arjuna Erat (sea), erat.simon@gmail.com
.. ....................................................
.TH "tui" 1 "2014-11-09" "Tui Version 0.6.0"

.SH NAME
TUI \- Text User Interface




.SH SYNOPSIS
...SY tui
...OP options
...RI [ arguments .\|.\|.]
.br
source \fBtui\fP | \fBtui\fP config




.SH DESCRIPTION
.PP
TUI is an abrevihation for "Text User Interface", it is a framework of commands to help you creating a line based text interface.

.br
It enables you to write scripts which when using the tui-'simulation a TUI in any terminal window or tty console.
.br
Due to the 'limitation's of a VT or a Terminal window, it is a line-based-interface.
.br
It is ment for scripts that  want to present themself a little bit more attractive to endusers.

Do not get overhelmed by the many commands provided by TUI.
.br
It is just based upon these 4 commands, all other commands are just assistants for specific tasks, to help you match them into TUI, or to ease some very repeative tasks.
.br
All of these 4 commands share some behaviour:
.br
.B
1.
You may pass from none to 3 strings.
.br
.B
2. 
String alignment:
.RS 4
0 strings will print the borders, and colors where applicable, but no strings
.br
1 string will be left aligned
.br
2 strings will be first on the left, second on the right side aligned.
.br
3 strings will be first on the left, second in the middle, third on the right side aligned.


.IP "\fBtui-printf\fP"
The very core of TUI. It works with 'echo-like' syntax, but without ending <newline>.
.br
As long it fits on a single line, each additional call of tui-printf will be replacing its previous one.
.br
Otherwise it will attemp to print the last available string on a new line, 
if only one is available, it will split it up equaly.


.IP "\fBtui-echo\fP"
Prints up to three strings on the same line, and an ending <newline>.

.IP "\fBtui-header\fP"
Prints a blue background with white font, filling complete line.

.IP "\fBtui-title\fP"
Prints the first string in the middle.
.br
Prints a white background with blue font inlined of the borders
.br




.SH OPTIONS
All of the tui-* commands, share a common option trigger, which is:
.br
.OP \-h
	Shows command version and help
.br

Please see their respective help or manpage information for their options and syntax.




.SH TEXT USER INTERFACE
Sourcing TUI by either
.B
.I ". tui"
or
.B
.I "source tui"
will provide the variables listed in the 
.B FILES 
section.

.SH FILES
These files are used as settings and user customization.
.br
Generaly speaking, these are ment so the user configures the 'endpoints' (theme, applications), 
and the developer can focus on writing functions, and simply use tui-edit instead of looking which text 
editor is installed, and wether or not the user is in graphical interface.
.br

If you want to change settings, please use:
.B
tui config
.br


.IP \fI/etc/tui/\fP
System wide defaults
.br
.RS 7
.IP \fBapps.conf\fP
(tui-edit, tui-web, tui-terminal)
.br
This stores the default applications tui might want/need to interact with
.br
.I
Provides:
.RS 11
.IP BROSER_CLI
The internetbrowser for the CLI, default: w3m
.IP BROWSER_GUI
The internetbrowser for the Graphical Interface, default: firefox
.IP EDITOR_CLI
Your favorite console editor, default: nano
.IP EDITOR_GUI
Your favorite graphical editor, default: leafpad
.IP FILEMGR
Name of your favorite filebrowser, default: pcmanfm
.IP TERMINAL
Name of your favorite terminal window, default: xterm
.IP TAR_EXT
Default extension used by 
.B tui-tar
, defaults: tar.gz
.IP DD_BS
Bytesize used by 
.B tui-dd
to read and write per cycle, default: 4M
.br
.RE

.IP \fBcolors.conf\fP
(tui-header, tui-title)
.br
Contains a list of colors.
.br
You could change them, but it is highly recomended not to do so!
.br
.I
Provides:
.br
.RS 11
.IP TUI_COLOR_RESET
Resets any color settings upon echo.
.IP TUI_RESET
Resets any color settings upon echo. (lazy)
.IP TUI_FONT_BOLD
Makes the font bold
.IP TUI_FONT_STRIKE
Makes the font stroke-through
.IP TUI_FONT_INVERT
Inverts the color settings
.IP TUI_FONT_UNDERSCORE
Underlines the text

.IP TUI_COLOR_{BG,FG}_{COLORNAME}
Where the color names are: 
.B BLACK BLUE CYAN GREEN GREY RED WHITE YELLOW 
.br
As in:
.br
TUI_COLOR_BG_WHITE
.br
TUI_COLOR_FG_BLACK
.RE

.IP \fBstatus.conf\fP
(tui-status)
.br
Defines how tui-status will report the different statuses
.br
Note that (for example): TUI_DONE contains the string, where RET_DONE contains an integer value. 
.br
.I
Provides:
.br
.RS 11
.IP {RET,TUI}-DONE
0
.br
[ DONE ]
.IP {RET,TUI}-FAIL
1
.br
[ FAIL ]
.IP {RET,TUI}-WORK
2
.br
[ WORK ]
.IP {RET,TUI}-TODO
3
.br
[ TODO ]
.IP {RET,TUI}-SKIP
4
.br
[ SKIP ]
.IP {RET,TUI}-NEXT
5
.br
[ NEXT ]
.IP {RET,TUI}-BACK
6
.br
[ BACK ]
.IP {RET,TUI}-CANC
7
.br
[ DONE ]
.IP {RET,TUI}-ON
10
.br
[  ON  ]
.IP {RET,TUI}-OFF
11
.br
[ OFF  ]
.IP {RET,TUI}-HELP
99
.br
[ HELP ]
.IP {RET,TUI}-INFO
111
.br
[ INFO ]
.RE

.IP \fBtui.conf\fP
(tui-new-browser, tui-new-script)
.br
Some basic configurations, like TUI_TEMP_{DIR,FILE}
.br
.I
Provides:
.br
.RS 11
.IP THE_THEME
Name of the default theme for the users, default (blue): default
.IP TUI_THEME_ROOT
Name of the theme for the root user, default (red): default-red
.IP TUI_CONF
Full path to itself
.IP TUI_USER_CONF
Full path to the user configuration file: ~/.config/tui/user.conf
.IP TUI_USER_TEMPLATE
Path to the templates for a new user: /usr/share/tui/user.conf/
.IP TUI_TEMP_DIR
Full path to first temp path existing
.IP TUI_TEMP_FILE
Full path to a file in $TUI_TEMP_DIR
.IP DEFAULT_LICENSE
Default licensing for tui-new-script, default: "GNU General Public License (GPL)"
.IP DEFAULT_LICENSE_URL
URL to the license, default: "http://www.gnu.org/licenses/gpl.html"
.RE

.IP \fI~/.config/tui/\fP
Personal user configuration

.br
.RS 7
.IP \fBapps.conf\fP
(tui-edit, tui-web, tui-terminal)
.br
Personal favorite applications, will overwrite the system wide defaults
.br
.I
Provides: 
.B
The same as /etc/tui/apps.conf 


.IP \fBuser.conf\fP
(tui-new-browser, tui-new-script)
.br
Some basic reusable info about you, so you can easly reuse these information inside your own scripts.
.br
.I
Provides:
.br
.RS 11
.IP USER_NAME
Default username shown, default: $USER
.IP USER_EMAIL
Default email used, default: $USER AT $(hostname)
.IP USER_HOMEPAGE
Default URL shown when $USER_HOMEPAGE is used
.IP DEFAULT_LICENSE
Default licensing for tui-new-script, default: "GNU General Public License (GPL)"
.IP DEFAULT_LICENSE_URL
URL to the license, default: "http://www.gnu.org/licenses/gpl.html"
.IP TUI_THEME
The actualy theme name the user uses, default: $TUI_THEME
.RE


.SH SEE ALSO
.PP
.B tui-bgjob
(1),
.B tui-bol-dir
(1),
.B tui-browser
(1),
.B tui-conf-editor
(1),
.B tui-conf-get
(1),
.B tui-conf-set
(1),
.B tui-dd
(1),
.B tui-download
(1),
.B tui-echo
(1),
.B tui-edit
(1),
.B tui-header
(1),
.B tui-indi
(1),
.B tui-install
(1),
.B tui-list
(1),
.B tui-log
(1),
.B tui-new-browser
(1),
.B tui-new-script
(1),
.B tui-press
(1),
.B tui-printf
(1),
.B tui-progress
(1),
.B tui-psm
(1),
.B tui-read
(1),
.B tui-status
(1),
.B tui-str-usb
(1),
.B tui-tar
(1),
.B tui-title
(1),
.B tui-wait
(1),
.B tui-yesno
(1)




.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html




...SH "KNOW BUGS"
...IP "item 1"
...br
..text of item 1
...IP "item 2"
...br
..text of item 2




.SH BUG REPORTS
Please visit "https://github.com/sri-arjuna/tui/issues" to report bugs,
.br
or send me an email to the adress listed in
.B
CONTACT



...SH AUTHORS
...IX Header "AUTHORS"
..Simon Arjuna Erat (sea), Organisation/Club/Title
...br
..http://linux-scripter.blogspot.com



.SH CONTACT
Simon Arjuna Erat (sea), erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
