# ------------------------------------------------------------------------
# Copyright (c) 2015 Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
# ------------------------------------------------------------------------
#
#	TUI - Configuration file - Apps
#
#
#	This file is part of the 'tui' package and is ment to be changed.
#
#	Default applications
#
	# tui-web
	BROWSER_CLI=lynx
	BROWSER_GUI=icecat
	
	# tui-download
	CURLWGET=curl
	
	# tui-edit
	EDITOR_CLI=nano
	EDITOR_GUI=gedit
	
	# tui-filemgr
	FILEMGR_GUI=nautilus
	FILEMGR_CLI=tui-browser
	
	# tui-terminal
	TERMINAL=xterm
