#!/bin/bash
source tui

cat > "$DEST" << EOF
#!/bin/bash
# File: 	${DEST##*/}
# Description:	
# $DEFAULT_LICENSE $(date +'%Y') by $USER_NAME ($USER_EMAIL)
# ------------------------------------------------------
#
#	Variables
#
	
#
#	Functions
#
	
#
#	Action & Display
#
	
EOF
