#!/usr/bin/env bash
source tuirc

cat > "$DEST" << EOF
#!/usr/bin/env  $USER_SHELL
# File: 	${DEST##*/}
# Description:	
# $DEFAULT_LICENSE $(date +'%Y') by $USER_NAME ($USER_EMAIL)
# ------------------------------------------------------
#
#	Variables
#
	
#
#	Functions
#
	
#
#	Action & Display
#
	
EOF
