#!/usr/bin/env bash
# ----------------------------------------------------------------------
# Copyright (c) 2013-2015 Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANT ABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
# ----------------------------------------------------------------------
source tuirc

cat > "$DEST" << EOF
#!/usr/bin/env bash
# ------------------------------------------------------------------------
#
# Copyright (c) $(date +'%Y') by $USER_NAME, $USER_EMAIL
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the $DEFAULT_LICENSE as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# $DEFAULT_LICENSE for more details.
#
# You should have received a copy of the $DEFAULT_LICENSE
# along with this program.  If not, see $DEFAULT_LICENSE_URL
#
# ------------------------------------------------------------------------
#
#	TUI Internals
#
	script_version=0.1
	script_created="$(date +'%Y.%m.%d')"
	script_changed="$(date +'%Y.%m.%d')"
	
	script_name="\${0##*/}"
	script_name="\${script_name/.sh/}"
	script_title="${DEST##*/}"
	script_package=""
	script_url="$USER_HOMEPAGE"
	
	script_author="$USER_NAME"
	script_contact="$USER_EMAIL"
	script_license="$DEFAULT_LICENSE"
#
#	Internal preps
#
	[ ! -z "\$script_package" ] && script_package+=" " && script_package_txt=" ($script_package)"
#
#	Shared variables & Language
#
	# Check the two default places for the core configuration
	# First systemwide, second user only install
	for tmp_task in "/etc" "/usr/local" "\$HOME" "\${HOME:-/root}/.local" 
	do 	[ -f "\$tmp_task/tui.conf" ] && source "\$tmp_task/tui.conf" && [ ! -z "\${SYSCONFDIR}!" ] && break
	done
	# Get the main config files
	if source "\${SYSCONFDIR}/tuirc" && source "\${HOME:-/root}/.tuirc" 2>/dev/zero
	then 	# Load required variables
		source "\$TUI_FILE_CONF_COMMANDS"
	else	source tuirc
	fi
	break_on_injections "$@" && exit 1
	source gettext.sh
	TEXTDOMAIN="\$script_name"
	TEXTDOMAINDIR="\${TUI_DIR_SYSTEM/tui/locale}"	# Assuming \$script_package is installed to \$TUI_DIR_SYSTEM as well...
	export TEXTDOMAIN TEXTDOMAINDIR
#
#	Variables
#
	typeset -r CFG="\$script_config"
	typeset -r LOG="\$TUI_DIR_LOGS/\${script_name}.log"
	delcare TMP="\${TUI_DIR_TEMP:-TMPDIR}/\${script_name}-\$\$.tmp~"
#
#	Messages to translate:
#
	MSG_TR_VERSION="\$(eval_gettext '\${script_name}\${script_package_txt}, Version \$script_version
Copyright (C) $(date +'%Y') $USER_NAME
License $DEFAULT_LICENSE or later <$DEFAULT_LICENSE_URL>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
')"
	MSG_TR_HELP="\$(eval_gettext '
NAME
  $script_name - SHORTDESC

SYNOPSYS
  $script_name [-h|--help] [--version] [-abcx] [--option] [--more opt]
  
DESCRIPTION
  desc
  
OPTIONS
  -h|--help	Shows help and exit with 99
  --version	Shows version infoand exit with 0
  
  -a		Some
  -b		more
  -c		text
  --more opt	desc
 
EXAMPLE

	code

HINTS
  Some_text
  
SEE ALSO
  tuirc(1), txt2man(1), gettext(1)
  
BUGS
  Report bugs to: mailinglist ; <$USER_EMAIL>
  
  $script_name - Homepage: <$USER_HOMEPAGE>
  
  General help using GNU software: <http://www.gnu.org/gethelp/>

AUTHOR
  $USER_NAME, <$USER_HOMEPAGE>
')"
	MSG_TR_XY="\$(gettext '')"
	MSG_TR_XX="\$(gettext '')"
	MSG_TR_YY="\$(eval_gettext '')"
#
#	Functions
#
	cleanup() { 
	# Removes all known tempfiles and exits
	# Is called at the end of the script and by the trap
		declare -a arr_CLEANUP=(
			"\$TMP"
			# Add your tempfiles
			# here
			)
		for remove in "\${arr_CLEANUP[@]}"
		do 	( [ -f "\$remove" ] || [ -p "\$remove" ] ) && rm -f "\$remove"
		done
	}
	show_help() {
	# Prints the helpscreen
	# and exits
		echo "\$MSG_TR_HELP_LONG"
		exit 99
	}
	show_version() {
	# Prints the version of the script
	# and exits
		echo "\$MSG_TR_VERSION"
		exit 111
	}
#
#	Traps are cool!
#
	# TRAP FUNCTION/"COMMAND" MODE's ...
	trap cleanup INT ERR QUIT KILL ABRT
#
#	Get options
#
	# -a|--alternative ; to allow longoptions with a single leading '-'
	GETOPT=\$(getopt \\
		--options	"h" \\
		--longoptions	"help,version,YOUROPT:" \\
		--name 		"\${0##*/}" -- "\${@}" \\
	)
	eval set -- "\${GETOPT}";
	while true
	do 	case "\$1" in
		-h|--help)	show_help	;;
		--version)	show_version	;;
		--)		shift ; break	;;
		# --------------------------------
		--YOUROPT)	opt_str="\$2"
				shift 2
				;;
		esac
	done
#
#	Action
#
	# TODO
#
#	Display
#
	tui-header "\$script_name (\$script_version)" "\$(date +'%F %T')"
	tui-title "\$script_title"
	tui-echo "\$MSG_XY"
	
#
# 	Clean up & exit
#
	cleanup
	exit 0
EOF
