#!/usr/bin/env bash
# ----------------------------------------------------------------------
# Copyright (c) 2013-2015 Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANT ABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
# ----------------------------------------------------------------------
source tuirc

cat > "$DEST" << EOF
#!/usr/bin/env bash
# ------------------------------------------------------------------------
#
# Copyright (c) $(date +'%Y') by $USER_NAME, $USER_EMAIL
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the $DEFAULT_LICENSE as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# $DEFAULT_LICENSE for more details.
#
# You should have received a copy of the $DEFAULT_LICENSE
# along with this program.  If not, see $DEFAULT_LICENSE_URL
#
# ------------------------------------------------------------------------
#
#	Description:
#	TODO text here ....
#
#
#
#	TUI
#
	source tuirc
	script_name="\${0##*/}"
	script_name="\${script_name/.sh/}"
	script_title="${DEST##*/}"
	script_author="$USER_NAME"
	script_contact="$USER_EMAIL"
	script_license="$DEFAULT_LICENSE"
	script_created="$(date +'%Y.%m.%d')"
	script_changed="$(date +'%Y.%m.%d')"
	script_version=0.1
	# Optional
	script_config="\$HOME/.config/\$script_name/\$script_name.conf"
	[ ! "." = "\$(dirname \$0)" ] && \\
		script_dir="\$(dirname \$0)" || \\
		script_dir="\$(pwd)"
	LOG="\$TUI_DIR_LOGS/\${script_name}.log"
	TMP="\${TMPDIR}/\${script_name}-\$\$.tmp~"
#
#	Variable Defaults & Inits
#
	default_var="default value"
#
#	Functions
#
	cleanup() { 
	# Removes all known tempfiles and exits
	# Is called at the end of the script and by the trap
		tmp_KNOWN=(
			"\$TMP"
			# Add your tempfiles
			# here
			)
		for remove in "\${tmp_KNOWN[@]}"
		do 	[ -f "\$remove" ] && rm -f "\$remove"
		done
	}
	show_help() {
	# Prints the helpscreen
	# and exits
		MSG_TR_HELP="Usage:	\$script_name [options] arguments ...
Options:
	-h|--help		Shows this screen and exits
	--version		Shows the version and exits
	--YOUROPT ARG		Sets 'opt_str' to ARG
	"
		echo "\$MSG_TR_HELP"
		exit 99
	}
	show_version() {
	# Prints the version of the script
	# and exits
		MSG_TR_VERSION="\$script_name, Version \$script_version
Copyright (C) $(date +'%Y') $USER_NAME
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
"
		echo "\$MSG_TR_VERSION"
		exit 111
	}
#
#	Traps are cool!
#
	## TRAP FUNCTION/"COMMAND" MODE's ... ##
	trap cleanup ERR EXIT INT QUIT TERM
#
#	Get options
#
	# -a|--alternative ; to allow longoptions with a single leading '-'
	GETOPT=\$(getopt \\
		--options	"h" \\
		--longoptions	"help,version,YOUROPT:" \\
		--name 		"\${0##*/}" -- "\${@}"
	)
	eval set -- "\$GETOPT"
	while true
	do 	case "\$1" in
		-h|--help)	show_help	;;
		--version)	show_version	;;
		--)		shift ; break	;;
		--YOUROPT)	opt_str="\$2"
				shift 2
				;;
		esac
	done
#
#	Action & Display
#
	tui-header "\$script_name (\$script_version)" "\$(date +'%F %T')"
	tui-title "\$script_title"
	tui-echo "Hello world!"
#
# 	Clean up & exit
#
	cleanup
	exit 0
EOF
