#!/usr/bin/env bash
source tui

cat > "$DEST" << EOF
#!/usr/bin/env bash
# ------------------------------------------------------------------------
#
# Copyright (c) $(date +'%Y') by $USER_NAME, $USER_EMAIL
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the $DEFAULT_LICENSE as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# $DEFAULT_LICENSE for more details.
#
# You should have received a copy of the $DEFAULT_LICENSE
# along with this program.  If not, see $DEFAULT_LICENSE_URL
#
# ------------------------------------------------------------------------
#
	source "\$HOME/.tui_rc" || . tui
	for config in \$TUI_FILE_{CONF,USER}_{APPS,COMMANDS,COLORS,USER,SETTINGS,STATUS,SYSTEM}
	do	[ -f "\$config" ] && source "$config"
	done
#
#	File:		${DEST##*/}
#	Author: 	$USER_NAME
#	Contact:	$USER_EMAIL
#	License:	$DEFAULT_LICENSE
#	Created:	$(date +'%Y.%m.%d')
#	Changed:	$(date +'%Y.%m.%d')
	script_version=0.0.1
	TITLE="${DEST##*/}"
#	Description:	Text TODO
#
#
#	Script Environment
#
	ME="\${0##*/}"				# Basename of ${DEST##*/}
	ME="\${ME/.sh/}"				# Cut off .sh extension
	[ ! "." = "\$(dirname \$0)" ] && \\
		ME_DIR="\$(dirname \$0)" || \\
		ME_DIR="\$(pwd)"			# Dirname of ${DEST##*/}
	CONFIG_DIR="\$HOME/.config/\$ME"		# Configuration directory
	CONFIG="\$CONFIG_DIR/\$ME.conf"			# Configuration file
	TEMPFILE="\$TUI_TEMP_DIR/\$ME.tmp"		# Tempfile
#
#	Help text
#
#	TODO
#	Add your own options, be sure to add them to "getopts" handling too
#
	help_text="
\$ME (\$script_version)
\${TITLE^}
Usage: 		\$ME [options] arguments
Examples:	\$ME 
		\$ME -a
		\$ME -e optVAL
Where options are:
	-h(elp) 		This screen
	

"
#
#	Functions
#
	
#
#	Catching Arguments
#
	# A ':' after a char indicates that this option requires an argument
	# Get access to the passed value of the argument by using \$OPTARG
	while getopts "h" opt
	do 	case \$opt in
		h)	printf "\$help_text"
			exit \$RET_HELP
			;;
		*)	printf "\$help_text" 
			exit 1
			;;
		esac
	done
	shift \$((\$OPTIND - 1))	# All options and they (if applicable) mandatory argument are removed
	ARGS=("\${*}")			# Remaining arguments
	ARGS_COUNT=\${#ARGS[@]}		# Amount of remaining
#
#	Action & Display
#
	tui-header "\$ME (\$script_version)" "\$(date +'%F %T')"
	tui-title "\$TITLE"
	
#
# 	Clean up & exit
#
	[ -f "\$TEMPFILE" ] && rm -fr "\$TEMPFILE"
	exit 0
EOF
