#!/usr/bin/env bash
MORE_OPTS=""
[ -z $APP_USER_LABEL ]	|| MORE_OPTS+=" -u \"$APP_USER_LABEL\""
[ -z $APP_FILES ]	|| MORE_OPTS+=" -F \"$APP_FILES\""
[ -z $APP_FOLDERS ]	|| MORE_OPTS+=" -D \"$APP_FOLDERS\""
[ -z $APP_SCRIPTS ] 	|| MORE_OPTS+=" -s \"$APP_SCRIPTS\""
cat << EOF
#!/usr/bin/env bash
# Project: $APP_TITLE ($APP_FILE)
#
# Copyright (c) $(date +%Y) $USER_NAME < $USER_EMAIL >
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
# ------------------------------------------------------------------------
#
#	Description:	Starts the project $APP_TITLE
#	Author:		$USER_NAME < $USER_EMAIL >
#	Date:		$(date +'%F')
#
#	$APP_TITLE requires TUI - Text User Interface by Simon Arjuna Erat (sea)
#	Check if TUI is installed...
#
	if S=$(which tui) 2>/dev/zero # [ ! -f "\$S" ]
	then 	[ ! 0 -eq \$UID ] && \\
			printf "\\n#\\n#\\tPlease restart the script (\${0##*/}) as root to install TUI (Text User Interface).\\n#\\n#\\n" && \\
			exit 1
		if ! git clone https://github.com/sri-arjuna/tui.git /tmp/tui.inst
		then 	mkdir -p /tmp/tui.inst ; cd /tmp/tui.inst/
			curl --progress-bar -L https://github.com/sri-arjuna/tui/archive/master.zip -o master.zip
			unzip master.zip && rm -f master.zip
			mv tui-master/* . ; rmdir tui-master
		fi
    		bash /tmp/tui.inst/install.sh || \\
    			(printf "\\n#\\n#\\tPlease report this issue of TUI installation fail.\\n#\\thttps://github.com/sri-arjuna/tui/issues\\n#\\t$(bash --version)\\n#\\n#\\n";exit 1)
    	fi
    	source \$S ; unset S
#
#	Variables
#
	ME_VERSION=0.1
	ME="\${0##*/}"
	ME_DIR="\${0/\${0##/*/}}"
	ME_BASE="$APP_BASE/$APP_MENU"
	TITLE="$APP_TITLE (\$ME_VERSION)"
	MORE_OPTS="$MORE_OPTS"
#
#	Help text
#
	help_text="
\$ME (\$ME_VERSION)
\${TITLE^}
Usage: 		\$ME [options] arguments
Examples:	\$ME help
		\$ME 
Where options are:
	-h(elp) 		This screen
"
	case \$1 in
	-h|--help)	printf '%s\n' "\$help_text"
			exit 99
			;;
	esac
#
#	Action and Display
#
	tui-browser \\
		-p "\$ME_BASE" \\
		-T "\$TITLE" \\
		\$MORE_OPTS "\${@}"
EOF
