#!/bin/bash
MORE_OPTS=""
[[ -z $APP_USER_LABEL ]] || MORE_OPTS+=" -u '$APP_USER_LABEL'"
[[ -z $APP_FILES ]]	|| MORE_OPTS+=" -d '$APP_FILES'"
[[ -z $APP_FOLDERS ]]	|| MORE_OPTS+=" -f '$APP_FOLDERS'"
[[ -z $APP_SCRIPTS ]] 	|| MORE_OPTS+=" -s '$APP_SCRIPTS'"
cat << EOF
#!/bin/bash
#	Description:	
#	
#	Author: 	$USER_NAME < $USER_EMAIL >
#	Date:		$(date +'%F')
#
#	This script requires TUI - Text User Interface & tui-browser  by (sea)
#	Check if TUI is installed...
#
	S=/etc/profile.d/tui.sh
	if [[ ! -f \$S ]]
	then 	[[ ! 0 -eq \$UID ]] && \\
			printf "\\n#\\n#\\tPlease restart the script as root to install TUI (Text User Interface).\\n#\\n#\\n" && \\
			exit 1
		if ! git clone https://github.com/sri-arjuna/tui.git /tmp/tui.inst
		then 	mkdir -p /tmp/tui.inst ; cd /tmp/tui.inst/
			curl --progress-bar -L https://github.com/sri-arjuna/tui/archive/master.zip -o master.zip
			unzip master.zip && rm -f master.zip
			mv tui-master/* . ; rmdir tui-master
		fi
    		sh /tmp/tui.inst/install.sh || \\
    			(printf "\\n#\\n#\\tPlease report this issue of TUI installation fail.\\n#\\n#\\n";exit 1)
    	fi
    	source \$S ; S=""
#
#	Variables
#
	APP_VERSION=0.1
	ME="\${0##*/}"
	ME_DIR="\${0/\${0##/*/}}"
	ME_BASE="$APP_BASE/$APP_DATA"
	TITLE="$APP_TITLE (\$APP_VERSION)"
	MORE_OPTS="$MORE_OPTS"
#
#	Help text
#
	help_text="
\$ME (\$script_version)
\${TITLE^}
Usage: 		\$ME [options] arguments
Examples:	\$ME 
		\$ME 
Where options are:
	-h(elp) 		This screen
"
	case $1 in
	-h|--help)	printf '%s\n' "\$help_text"
			exit 99
			;;
	esac
#
#	Display to user
#
	#cd "\$ME_BASE"
	tui-browser \\
		-p "\$ME_BASE" \\
		-t "\$TITLE" \\
		\$MORE_OPTS
EOF
