#!/usr/bin/env bash
# -- Sample script to use with likewise named command --
#
#	Variables
#
	IAM_SAMPLE="${0##*/}"
	tui-title "$IAM_SAMPLE samples"
#
#	List entries of a list
#
	tui-title "Sample: #1"
	tui-read "Enter some text"
#
#	Print the list with 2 columns with roman counting
#
	tui-echo
	tui-title "Sample: #2"
	eye_color=$(tui-read "What is your eyecolor?")
	tui-echo "Your eyecolor is:" "$eye_color"
#
#	Print the list with 1 columns with alphabetic counting
#
	tui-echo
	tui-title "Sample: #3"
	password=$(tui-read -p "Enter a theoretical password:" )
	tui-echo "The password is:" "$password"
	