#!/usr/bin/env bash
# This file belongs to the package GNU TUI (0.9.0 or later), which is copyrighted by the GPLv3 (or later).
#
#	Vars
#
	LETTERS="$(echo {a..g})"
	NUMBERS="$(echo {25..42})"
#
#	Action
#
	tui-title "Single column"
	tui-list -1 $LETTERS
	
	tui-title "Two columns numbered
	tui-list -2n $LETTERS
	
	tui-title "Automatic columns numbered with roman letters"
	tui-list -r $LETTERS

	tui-title "Two columns with alpha numeric numbering"
	tui-list -2a $NUMBERS

	tui-title "List content of current directory"
	ls | tui-list -n1