#!/usr/bin/env bash
# This file belongs to the package GNU TUI (0.9.0 or later), which is copyrighted by the GPLv3 (or later).
tui-header "TUIRC - Samples"	"tui-$1"

tui-title "Basic invocation"
tui-$1

tui-title "Example 2"
tui-$1

tui-title "Example 3"
tui-$1

tui-title "Example 4"
tui-$1

tui-title "Example 5"
tui-$1

tui-title "Example 6"
tui-$1
