#!/usr/bin/env bash
# This file belongs to the package GNU TUI (0.9.0 or later), which is copyrighted by the GPLv3 (or later).
tui-header "TUIRC - Samples"	"tui-printf"

tui-title "Basic invocation"
MSG="Print a line that replaced by the next, loop count:"
C=0
while [ $C -lt 25 ]
do 	tui-printf "$MSG $C"
	((C++))
	sleep 0.05
done
printf '\n'
tui-echo

tui-title "Example 2"
MSG="Can be used to illustrate the exit codes of tui-status, without the actual exit codes"
C=0
while [ $C -lt 131 ]
do 	tui-printf -rS $C "$MSG $C"
	case $C in
	0|1|2|3|4|5|6|7|10|11|99|111|127|130)
		sleep 0.7
		;;
	esac
	((C++))
	
done

tui-title "Example 3"
tui-printf -E "It is tui-echo as well"

tui-title "Example 4"
tui-printf -T "Or tui-title"

tui-title "Example 5"
tui-printf -E "" "Apply some" "custom alignment" 

tui-title "Example 6"
tui-printf -rS 111 "Or even tui-status..."
tui-printf -S 99 Hope, "this helps"
