#!/usr/bin/env bash
# This file belongs to the package GNU TUI (0.9.0 or later), which is copyrighted by the GPLv3 (or later).
tui-header "TUIRC - Samples"	"tui-filemgr"

tui-title "Basic invocation"
tui-filemgr .

tui-title "Example 2"
tui-filemgr "$HOME"

tui-title "Example 3"
source tuirc
tui-filemgr "$TUI_DIR_USER_SCRIPTS"