.TH "tui-dd"  1  "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-dd (0.5)

.SH SYNOPSIS
\fBtui-dd\fP SOURCE TARGET
.br

Example:
.br
		tui-dd /path/to/somefile.iso $(tui-str-usb)
.br
		tui-dd somefile.iso /dev/sdc

.SH DESCRIPTION
Writes SOURCE to TARGET using DD.
.br
Showing amount of data written during the process.

.SH SEE ALSO
dd(1), ps(1), bash(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com