.TH "tui-bgjob"  1  "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-bgjob (0.5)

.SH SYNOPSIS
\fBtui-bgjob\fP [-f OUTFILE] SCRIPTFILE  'Progress String'  'Exit String'  [ WAIT ]
.br

Examples:
.br
		tui-bgjob $HOME/script.sh "\\$(ls -l \\$some_var/FILE|awk '{print \\$5}')" "Script executed"
.br
		tui-bgjob scriptname "Working, please wait..." "Finished" 5
.br

.br
NOTE:\t'Progress String' may contain shell escaped commands.
.br
If
.B
-f OUTFILE
is passed, it will check for OUTFILE and print its 
.I filesize.

.SH DESCRIPTION
.PP
Executes SCRIPTFILE and prints 'Progress String' while running.
.br
Prints 'Exit String' when done, regardless of exit code (0,1,?).
.br
WAIT is the optinal wait time in seconds between updates, default is 0.7.

.SH SEE ALSO
ps(1), sh(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com