.TH "tui-select"  1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-select (0.1)

.SH DESCRIPTION
Tries to simulate regular select behaviour for TUI.

.SH SYNOPSIS
\fBtui-select\fP [options] LIST ARRAY[@] ...
.br
Examples:
.RS 8
.IP "tui-select yes no"
.IP "selected=$(tui-select *)"
.RE

.SH OPTIONS
.OP -a
.br
Autoselect if only 1 entry found


.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
