.TH "tui-str-bol-conv" "1" "2015-05-14" "sea"


.SH NAME
tui-str-bol-conv (0.1)


.SH SYNOPSIS
\fBtui-str-bol-conv\fP [options] [arguments]
.br
Example: tui-str-bol-conv $?
.br
Where options are:
.IP "\fB-h\fP"
Shows the help screen.
.IP "\fB-c\fP"
Makes returned strings starting with a capital letter
.br
.IP "\fB-C\fP"
Makes returned strings all capital letters
.br
.IP "\fB-d\fP"
Returns either: done or fail
.br
.IP "\fB-o\fP"
Returns either: on or off
.br
.IP "\fB-y\fP"
Returns either: yes or no
.br
.IP "\fB-t\fP"
Returns either: true or false
.br


.SH DESCRIPTION
.PP
Converts exit codes 0,1 into strings according to passed options.
.br
Default is: yes/no in favor of tui-yesno


.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html


.SH CONTACT
linux-scripter.blogspot.ch
.br

