.TH "tui-terminal" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-terminal (0.3)

.SH SYNOPSIS
\fBtui-terminal\fP 
.br

Example: 
.br
		\fBtui-terminal\fP 
.br
		\fBtui-terminal\fP 

.SH DESCRIPTION
Opens a new terminal window, GUI only.
.br

.SH FILES
.IP /etc/tui/apps.conf
Provides the favorite applications defaults for the system.
.IP ~/.config/tui/apps.conf
Provides the favorite applications defaults for the user.


.SH SEE ALSO
.B bash
(1),
.B tui
(1),
.B tui-edit
(1),
.B tui-filemngr
(1),
.B tui-terminal
(1),
.B tui-web
(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com