.TH "tui-bol-root" "1" "2015-05-16" "sea"

.SH NAME
tui-bol-root (0.1)

.SH SYNOPSIS
\fBtui-bol-root\fP
.br
Example: tui-bol-root && echo yes
.br

.SH DESCRIPTION
.PP
Returns true if $UID is 0.

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.erat@gmail.com

