.TH "tui-list" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-list (0.1)

.SH DESCRIPTION
Prints 1 item per line and numbering it

.SH SYNOPSIS
\fBtui-list\fP [options] item1 item2 item3 ...
.br

Example:
.br
		tui-list *

.SH OPTIONS
.OP -a
.br
Use letters instead of numbers

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
