.TH "tui-new-manpage.1" "1" "2014-12-12" "Simon Arjuna Erat (sea)"

.SH NAME
tui-new-manpage.1 (0.1)

.SH SYNOPSIS
\fBtui-new-manpage.1\fP [options] [arguments]
.br
Example: tui-new-manpage.1
.br
Where options are:
.IP "\fB-a\fP"
Creates a full \fBa\fPpplication manpage template.
.IP "\fB-m\fP"
Creates a full \fBm\fPinimal manpage template (default).

.SH DESCRIPTION
Eases the task to get a manpage, by providing some default infos.

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
