.TH "tui-asroot" "1" "2015-04-05" "Simon Arjuna Erat (sea)"

.SH NAME
tui-asroot (0.1)

.SH SYNOPSIS
\fBtui-asroot\fP [options] [arguments]
.br
Example: tui-asroot
.br
Where options are:
.IP "\fB-h\fP"
Prints this screen

.SH DESCRIPTION
.PP
Simply executes passed arguments as root.
.br
It first checks if user already is root, or if settings.conf has 
.B useSudo=true
it will call sudo.
.br
If neither of which, it invokes su -c "${@}"

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
