.TH "tui-bol-gui" "1" "2015-05-07" "Simon Arjuna Erat (sea)"

.SH NAME
tui-bol-gui (0.1)

.SH SYNOPSIS
\fBtui-bol-gui\fP [options]
.br
Example: tui-bol-gui
.br
Where options are:
.IP "\fB-h\fP"
Shows the helpscreen
.br
.IP "\fB-v\fP"
Shows the DE its name if it is a GUI.
.br

.SH DESCRIPTION
.PP
Returns true if the environment is a GUI.
.br
If verbose mode is enabled, and if it is a GUI, it reports which Desktop-Environment (DE) it is.
.br

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com
