.TH "tui-tar" 1 "Simon A. Erat (sea)" "TUI 0.7.3"

.SH NAME
tui-tar (0.7)

.SH SYNOPSIS
\fBtui-tar\fP [options] [[/path/to/]folder1] [[/path/to/]folder2] ...
.br

Example:
.br
	\fBtui-tar\fP /some/dir /another/dir-with/{reg,ex}
.br
Will create 2 tarballs, the first beeing named like:

.SH OPTIONS
.OP -b
.RS 4
Enables bar-mode
.RE

.SH DESCRIPTION
Tar's a complete folder, naming the tarball to the last subfolder-name.
.br


.SH FILES
.IP /etc/tui/apps.conf
Provides systemwide defaults for $TAR_EXT which is used as extension for tui-tar.
.IP ~/.config/tui/apps.conf
Provides the users setting for $TAR_EXT which is used as extension for tui-tar.


.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br

