.TH "tui-press" 1 "Simon A. Erat (sea)" "TUI 0.6.0"

.SH NAME
tui-press (0.2)

.SH SYNOPSIS
\fBtui-press\fP

.SH DESCRIPTION
Requires the user to press enter to continue, and prints "Press [ENTER] to continue"

.SH SEE ALSO
bash(1), read(1)

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT (BUGS)
erat.simon@gmail.com
.br
http://linux-scripter.blogspot.com